# typed: false
# frozen_string_literal: true

# This file is auto-generated by the CLI release workflow. Do not edit.
class Casedev < Formula
  desc "case.dev CLI — manage legal AI resources from the terminal"
  homepage "https://case.dev"
  version "0.0.1"
  license "MIT"

  if Hardware::CPU.arm?
    url "https://github.com/CaseMark/casedotdev-mono/releases/download/casedev-v0.0.1/casedev-darwin-arm64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  else
    url "https://github.com/CaseMark/casedotdev-mono/releases/download/casedev-v0.0.1/casedev-darwin-x64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  def install
    if Hardware::CPU.arm?
      bin.install "casedev-darwin-arm64" => "casedev"
    else
      bin.install "casedev-darwin-x64" => "casedev"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/casedev --version")
  end
end
