# This file was generated by GoReleaser. DO NOT EDIT.
cask "casedev" do
  name "casedev"
  desc "The official CLI for case.dev — manage legal AI resources from the terminal"
  homepage "https://case.dev"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "casedev"
  manpage "man/man1/casedev.1.gz"
  bash_completion "completions/casedev.bash"
  zsh_completion "completions/casedev.zsh"
  fish_completion "completions/casedev.fish"

  on_macos do
    on_intel do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_macos_amd64.zip"
      sha256 "c8c54326342b6f40cb812fab1f488b56102ee8911fd2a4d864860d7e489be855"
    end
    on_arm do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_macos_arm64.zip"
      sha256 "f186231cfa4a2ce8264f1d7a8ca320c8038124bb6135b7bbbfda75d3bc7d1094"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_linux_amd64.tar.gz"
      sha256 "11954756483ec99b89f48c7b86348443c4c4d5c42532c21ed35eaab91c1c57c3"
    end
    on_arm do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_linux_arm64.tar.gz"
      sha256 "430257b618ef325f790cbf4e3f4a7b2437c8078a35e12b5fd4eb8a7086df16dc"
    end
  end

  # No zap stanza required
end
