# This file was generated by GoReleaser. DO NOT EDIT.
cask "casedev" do
  name "casedev"
  desc "The official CLI for case.dev — manage legal AI resources from the terminal"
  homepage "https://case.dev"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "casedev"
  manpage "man/man1/casedev.1.gz"
  bash_completion "completions/casedev.bash"
  zsh_completion "completions/casedev.zsh"
  fish_completion "completions/casedev.fish"

  on_macos do
    on_intel do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_macos_amd64.zip"
      sha256 "abf596f8673f9dfd1669312649b32c13bf7cbc8fe5eb2061bdaec1e30c6f741c"
    end
    on_arm do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_macos_arm64.zip"
      sha256 "6365e5be52fffc183ecb28d709ceb5cf53333f24099c60eb8757a8262d7ea427"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_linux_amd64.tar.gz"
      sha256 "87eeaf0b01096a2c61cdd702e6507aa936edcdd50282da85941b8ce34897e4d7"
    end
    on_arm do
      url "https://github.com/CaseMark/casedev-cli/releases/download/v#{version}/casedev_#{version}_linux_arm64.tar.gz"
      sha256 "5289e279b743574995d8faa83c666ab50e43e2d5f6a7443a275ee170063a4d24"
    end
  end

  # No zap stanza required
end
